- hosts: all
  vars:
    zerotier_network_id: a0cbf4b62a2751e1
    zerotier_api_accesstoken: bMcxk1Cbh677EdCEVRYP9PVHZLWuYeAD
    zerotier_register_short_hostname: true
  roles:
    - name: m4rcu5nl.zerotier

- name: Plays for the client_basic group
  hosts: client_basic
  tasks:

    - name: Enable ufw
      community.general.ufw:
        state: enabled
        logging: on

    - name: Allow SSH for administration
      community.general.ufw:
        rule: allow
        name: OpenSSH

- name: Plays for the client_secure group
  hosts: client_secure
  tasks:

    - name: Enable ufw
      community.general.ufw:
        state: enabled
        logging: on
        policy: deny
        direction: outgoing

    - name: Allow SSH for administration
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Configure outbound rules
      community.general.ufw:
        rule: allow
        to_ip: '{{ hostvars[item].zerotier_member_ip_assignments[0] }}'
        direction: out
      with_items: "{{ groups['server_restricted'] }}"

- name: Plays for the server_basic group
  hosts: server_basic
  tasks:

    - name: Enable ufw
      community.general.ufw:
        state: enabled
        logging: on
        policy: deny
        direction: outgoing

    - name: Allow SSH for administration
      community.general.ufw:
        rule: allow
        name: OpenSSH
    
    - name: Configure inbound rules
      community.general.ufw:
        rule: allow
        to_port: 80
        proto: tcp
        from_ip: '{{ hostvars[item].zerotier_member_ip_assignments[0] }}'
        direction: in
      with_items: "{{ groups['all'] }}"

- name: Plays for the server_restricted group
  hosts: server_restricted
  tasks:

    - name: Enable ufw
      community.general.ufw:
        state: enabled
        logging: on
        policy: deny
        direction: outgoing

    - name: Allow SSH for administration
      community.general.ufw:
        rule: allow
        name: OpenSSH
    
    - name: Configure inbound rules
      community.general.ufw:
        rule: allow
        to_port: 80
        proto: tcp
        from_ip: '{{ hostvars[item].zerotier_member_ip_assignments[0] }}'
        direction: in
      with_items: "{{ groups['client_secure'] }}"