---

- include_tasks: install/{{ ansible_facts['os_family'] }}.yml
  tags:
  - installation
  - repositories

- block: #Install and enable zerotier-one
  - name: Install zerotier-one
    package:
      name: zerotier-one
      state: present
      update_cache: yes
    register: zerotier_client

  - name: Start zerotier-one service
    ansible.builtin.shell: service zerotier-one start

  when:
  - zerotier_repo is not defined or zerotier_repo is succeeded
  - not ansible_check_mode
  tags:
  - installation
  - packages
